### ISSUE TITLE
Que coisa feia, bruh

### ISSUE THREAD

**Issue by Crowley-Dev** [L4NBY/dados#1]
lamentável, esse tipo de programa não agrega em nada

**Comment by ReversiveDev** [comment]
@Crowley-Dev é um malware, por isso o código obfuscado.

**Comment by Crowley-Dev** [comment]
> @Crowley-Dev é um malware, por isso o código obfuscado.

Eu já li a source, sei do que o código se trata. Fork bomb não é malware.

**Comment by UserJV** [comment]
Mds, nem para fazer fork bomb serve.
